name: CI

on:
  push:

jobs:
  vet:
    name: Vet

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/go@v6

      - run: go vet

  release:
    name: Release
    needs: vet
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v6
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
